language: java

jdk: openjdk8

branches:
  only:
  - master


script:
- mvn clean install -DskipTests=false -P travis

after_success:
- bash <(curl -s https://codecov.io/bash)

env:
  global:
  - CODECOV_TOKEN=95bcd81b-35e2-415d-b96c-9b2ce769dbcf