language: java

jdk: openjdk8

branches:
  only:
  - master

before_install:
- pip install --user codecov

script:
- mvn clean install -DskipTests=false -P travis

after_success:
- bash <(curl -s https://codecov.io/bash)

env:
  global:
  - CODECOV_TOKEN=ce2eccce-be36-429b-8750-e12f8b2c12e2